{% set prefix = "spacy-model-" %}
{% set lang = "fr" %}
{% set name = lang + "_core_news" %}
{% set version = "3.0.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_sm-{{ version }}/{{ name }}_sm-{{ version }}.tar.gz
    sha256: 617339905472deda9a394fba9a41379231f40063c651e911236485b772624358
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_md-{{ version }}/{{ name }}_md-{{ version }}.tar.gz
    sha256: 9faa3e4a6ee8983bfc903dffb35c51a34e4ae68ad91639375a0da66172ca50f7

build:
  noarch: python
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
      commands:
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"

about:
  home: https://spacy.io
  license: CC BY-SA 3.0
  summary: French multi-task CNN trained on the French Sequoia (Universal Dependencies) and WikiNER corpus.

  doc_url: https://spacy.io/models/fr

extra:
  recipe-maintainers:
    - sodre
