{% set prefix = "spacy-model-" %}
{% set lang = "fr" %}
{% set name = lang + "_core_news" %}
{% set name_trf = lang + "_dep_news" %}
{% set version = "3.2.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_sm-{{ version }}/{{ name }}_sm-{{ version }}.tar.gz
    sha256: bcdd2c8c9ccef064f549298d2c5a4f1d22d96ba85011a989125ea4477fad9334
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_md-{{ version }}/{{ name }}_md-{{ version }}.tar.gz
    sha256: 3b09738b9060e4f857dacd93538921b5b54f0c0c514e43a06fbcd51933993fd8
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_lg-{{ version }}/{{ name }}_lg-{{ version }}.tar.gz
    sha256: 161ea065642af2daaf78283b4fbf8fe2fbacd3492f612047bd0b7301e0d4d055
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/{{ name_trf }}_trf-{{ version }}/{{ name_trf }}_trf-{{ version }}.tar.gz
    sha256: cd85b5d1b162a3125bf0986f920778b37ad30c71d46b1b2ce48717706b944157

build:
  noarch: python
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
      commands:
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"

about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: French multi-task CNN trained on the French Sequoia (Universal Dependencies) and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/fr

extra:
  recipe-maintainers:
    - FernandezMathieu
    - sodre
    - mxr-conda
    - JennaLipscomb
