{% set prefix = "spacy-model-" %}
{% set lang = "fr" %}

{% if size == "trf" %}
{% set name = lang + "_dep_news" %}
{% else %}
{% set name = lang + "_core_news" %}
{% endif %}

{% set version = "3.5.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-{{ version }}/fr_core_news_sm-{{ version }}.tar.gz
    sha256: f5ff599d0cc5abe4df1b8bf5a26a0e822b200d5c458f956241b3a9b3f3ab0aee
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-{{ version }}/fr_core_news_md-{{ version }}.tar.gz
    sha256: 14d24785c94a3daa1624b12efe83f1fbfaae9a688837ff1d493b2fb12f3207de
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_lg-{{ version }}/fr_core_news_lg-{{ version }}.tar.gz
    sha256: 04faef01572c614e7b225fb59d76f739efa9699efe35aa7e19ae03c310194efe
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/fr_dep_news_trf-{{ version }}/fr_dep_news_trf-{{ version }}.tar.gz
    sha256: 82be2aca1fefd75cb712a73d4451b5b305f9e33da5c6a97070a0bfc22c8d3e32

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}

    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}
      commands:
        {% if size == "trf" %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"  # [unix]
        {% else %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"
        {% endif %}

about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: French multi-task CNN trained on the French Sequoia (Universal Dependencies) and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/fr

extra:
  recipe-maintainers:
    - FernandezMathieu
    - sodre
    - mxr-conda
    - JennaLipscomb
