{% set prefix = "spacy-model-" %}
{% set lang = "fr" %}

{% if size == "trf" %}
{% set name = lang + "_dep_news" %}
{% else %}
{% set name = lang + "_core_news" %}
{% endif %}

{% set version = "3.4.0" %}

package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-{{ version }}/fr_core_news_sm-{{ version }}.tar.gz
    sha256: 79ede2c904ca1417a6f8440e7046773dd8b02d3ccaa101d32ae2aa88b7a501ef
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-{{ version }}/fr_core_news_md-{{ version }}.tar.gz
    sha256: c6c752f5a13b60c6219003d35a62e489eaf28ffccfe74028e2f3123be36eaec9
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/fr_core_news_lg-{{ version }}/fr_core_news_lg-{{ version }}.tar.gz
    sha256: f897c96f962b22ad3d7202c9afc954900cdb9c48334e3954d813de68cc0e44da
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/fr_dep_news_trf-{{ version }}/fr_dep_news_trf-{{ version }}.tar.gz
    sha256: b1db047699e678d63d729fa62f54d12c92521ca3c96614debfbc77c2bcf11d81

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}

    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}
      commands:
        {% if size == "trf" %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"  # [unix]
        {% else %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"
        {% endif %}

about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: French multi-task CNN trained on the French Sequoia (Universal Dependencies) and WikiNER corpus.
  license_file: LICENSE
  doc_url: https://spacy.io/models/fr

extra:
  recipe-maintainers:
    - FernandezMathieu
    - sodre
    - mxr-conda
    - JennaLipscomb
